import {
  Lightbulb,
  Pen,
  Zap,
  Target,
  Eye,
  Heart,
  Star,
  Rocket,
  Globe,
  Users,
  BookOpen,
  Code,
  Palette,
  Shield,
  TrendingUp,
  Award,
  CheckCircle,
  Compass,
  Layers,
  Database,
  Coffee,
  Music,
  Camera,
  Lock,
  Unlock,
  Key,
  Search,
  Settings,
  Bell,
  Mail,
  Phone,
  MapPin,
  Calendar,
  Clock,
  FileText,
  Image,
  Video,
  Mic,
  Headphones,
  Monitor,
  Smartphone,
  Tablet,
  Laptop,
  Wifi,
  Cloud,
  Download,
  Upload,
  Share,
  Link,
  ExternalLink,
  Copy,
  Trash,
  Edit,
  Plus,
  Minus,
  X,
  Check,
  AlertCircle,
  Info,
  HelpCircle,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  ChevronRight,
  ChevronLeft,
  ChevronUp,
  ChevronDown,
  BarChart,
  PieChart,
  Activity,
  Briefcase,
  DollarSign,
  ShoppingCart,
  Package,
  Truck,
  Store,
  Building,
  GraduationCap,
  FlaskConical,
  Microscope,
  Leaf,
  TreePine,
  Sun,
  Moon,
  CloudRain,
  Wind,
  Flame,
  Droplet,
  Mountain,
  Waves,
  Anchor,
  Flag,
  Medal,
  Trophy,
  Crown,
  Gem,
  Diamond,
  Hexagon,
  Triangle,
  Square,
  Circle,
  Octagon,
  Pentagon,
  Infinity,
  Percent,
  Hash,
  AtSign,
  Bookmark,
  Tag,
  Paperclip,
  Scissors,
  Ruler,
  Magnet,
  Battery,
  Plug,
  Power,
  Cpu,
  HardDrive,
  Printer,
  Keyboard,
  Mouse,
  Gamepad,
  Joystick,
  Film,
  Clapperboard,
  Tv,
  Radio,
  Podcast,
  Volume,
  VolumeX,
  Volume1,
  Volume2,
  Play,
  Pause,
  SkipForward,
  SkipBack,
  Repeat,
  Shuffle,
  Rewind,
  FastForward,
  LogIn,
  LogOut,
  User,
  UserPlus,
  UserMinus,
  Contact,
  IdCard,
  Badge,
  ShieldCheck,
  ShieldAlert,
  ShieldX,
  Swords,
  Crosshair,
  Fingerprint,
  Scan,
  Waypoints,
  Navigation,
  Map,
  Milestone,
  Signpost,
  Plane,
  Car,
  Bus,
  Bike,
  Ship,
  Train,
  Tractor,
  Accessibility,
  Baby,
  Hand,
  Footprints,
  PersonStanding,
  UsersRound,
  CircleDot,
  Orbit,
  Atom,
  Dna,
  TestTube,
  Pipette,
  Syringe,
  Pill,
  Thermometer,
  Stethoscope,
  HeartPulse,
  Bandage,
  Hospital,
  Ambulance,
  ScanEye,
  Glasses,
  Ear,
  EarOff,
  Brain,
  Bone,
  MemoryStick,
} from 'lucide-svelte';

/* eslint-disable @typescript-eslint/no-explicit-any */
const iconMap: Record<string, any> = {
  lightbulb: Lightbulb,
  pen: Pen,
  zap: Zap,
  target: Target,
  eye: Eye,
  heart: Heart,
  star: Star,
  rocket: Rocket,
  globe: Globe,
  users: Users,
  'book-open': BookOpen,
  code: Code,
  palette: Palette,
  shield: Shield,
  'trending-up': TrendingUp,
  award: Award,
  'check-circle': CheckCircle,
  compass: Compass,
  layers: Layers,
  database: Database,
  coffee: Coffee,
  music: Music,
  camera: Camera,
  lock: Lock,
  unlock: Unlock,
  key: Key,
  search: Search,
  settings: Settings,
  bell: Bell,
  mail: Mail,
  phone: Phone,
  'map-pin': MapPin,
  calendar: Calendar,
  clock: Clock,
  'file-text': FileText,
  image: Image,
  video: Video,
  mic: Mic,
  headphones: Headphones,
  monitor: Monitor,
  smartphone: Smartphone,
  tablet: Tablet,
  laptop: Laptop,
  wifi: Wifi,
  cloud: Cloud,
  download: Download,
  upload: Upload,
  share: Share,
  link: Link,
  'external-link': ExternalLink,
  copy: Copy,
  trash: Trash,
  edit: Edit,
  plus: Plus,
  minus: Minus,
  x: X,
  check: Check,
  'alert-circle': AlertCircle,
  info: Info,
  'help-circle': HelpCircle,
  'arrow-right': ArrowRight,
  'arrow-left': ArrowLeft,
  'arrow-up': ArrowUp,
  'arrow-down': ArrowDown,
  'chevron-right': ChevronRight,
  'chevron-left': ChevronLeft,
  'chevron-up': ChevronUp,
  'chevron-down': ChevronDown,
  'bar-chart': BarChart,
  'pie-chart': PieChart,
  activity: Activity,
  briefcase: Briefcase,
  'dollar-sign': DollarSign,
  'shopping-cart': ShoppingCart,
  package: Package,
  truck: Truck,
  store: Store,
  building: Building,
  'graduation-cap': GraduationCap,
  flask: FlaskConical,
  microscope: Microscope,
  leaf: Leaf,
  'tree-pine': TreePine,
  sun: Sun,
  moon: Moon,
  'cloud-rain': CloudRain,
  wind: Wind,
  flame: Flame,
  droplet: Droplet,
  mountain: Mountain,
  waves: Waves,
  anchor: Anchor,
  flag: Flag,
  medal: Medal,
  trophy: Trophy,
  crown: Crown,
  gem: Gem,
  diamond: Diamond,
  hexagon: Hexagon,
  triangle: Triangle,
  square: Square,
  circle: Circle,
  octagon: Octagon,
  pentagon: Pentagon,
  infinity: Infinity,
  percent: Percent,
  hash: Hash,
  '@': AtSign,
  bookmark: Bookmark,
  tag: Tag,
  paperclip: Paperclip,
  scissors: Scissors,
  ruler: Ruler,
  magnet: Magnet,
  battery: Battery,
  plug: Plug,
  power: Power,
  cpu: Cpu,
  'hard-drive': HardDrive,
  printer: Printer,
  keyboard: Keyboard,
  mouse: Mouse,
  gamepad: Gamepad,
  joystick: Joystick,
  film: Film,
  clapperboard: Clapperboard,
  tv: Tv,
  radio: Radio,
  podcast: Podcast,
  volume: Volume,
  'volume-x': VolumeX,
  volume1: Volume1,
  volume2: Volume2,
  play: Play,
  pause: Pause,
  'skip-forward': SkipForward,
  'skip-back': SkipBack,
  repeat: Repeat,
  shuffle: Shuffle,
  rewind: Rewind,
  'fast-forward': FastForward,
  'log-in': LogIn,
  'log-out': LogOut,
  user: User,
  'user-plus': UserPlus,
  'user-minus': UserMinus,
  contact: Contact,
  idcard: IdCard,
  badge: Badge,
  'shield-check': ShieldCheck,
  'shield-alert': ShieldAlert,
  'shield-x': ShieldX,
  swords: Swords,
  crosshair: Crosshair,
  fingerprint: Fingerprint,
  scan: Scan,
  waypoint: Waypoints,
  navigation: Navigation,
  map: Map,
  milestone: Milestone,
  signpost: Signpost,
  plane: Plane,
  car: Car,
  bus: Bus,
  bike: Bike,
  ship: Ship,
  train: Train,
  tractor: Tractor,
  accessibility: Accessibility,
  baby: Baby,
  hand: Hand,
  footprints: Footprints,
  'person-standing': PersonStanding,
  'users-round': UsersRound,
  'circle-dot': CircleDot,
  orbit: Orbit,
  atomic: Atom,
  dna: Dna,
  'test-tube': TestTube,
  pipette: Pipette,
  syringe: Syringe,
  pill: Pill,
  thermometer: Thermometer,
  stethoscope: Stethoscope,
  'heart-pulse': HeartPulse,
  bandage: Bandage,
  hospital: Hospital,
  ambulance: Ambulance,
  'scan-eye': ScanEye,
  glasses: Glasses,
  ear: Ear,
  'ear-off': EarOff,
  brain: Brain,
  bone: Bone,
  'memory-stick': MemoryStick,
};

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export function resolveIcon(name: string | null | undefined): any {
  if (!name) return null;
  return iconMap[name.toLowerCase()] ?? null;
}

export const iconKeys = Object.keys(iconMap).sort();
